schema-version = "1.10.0"

[install]
"automated-plan-reviser-pro".flake = "github:RogerNavelsaker/nixpkg-automated-plan-reviser-pro"
"beads-rust".flake = "github:RogerNavelsaker/nixpkg-beads-rust"
"beads-viewer".flake = "github:RogerNavelsaker/nixpkg-beads-viewer"
"cass-memory-system".flake = "github:RogerNavelsaker/nixpkg-cass-memory-system"
"coding-agent-session-search".flake = "github:RogerNavelsaker/nixpkg-coding-agent-session-search"
"coding-agent-account-manager".flake = "github:RogerNavelsaker/nixpkg-coding-agent-account-manager"
"cross-agent-session-resumer".flake = "github:RogerNavelsaker/nixpkg-cross-agent-session-resumer"
"destructive-command-guard".flake = "github:RogerNavelsaker/nixpkg-destructive-command-guard"
"mcp-agent-mail-rust".flake = "github:RogerNavelsaker/nixpkg-mcp-agent-mail-rust"
"meta-skill".flake = "github:RogerNavelsaker/nixpkg-meta-skill"
"named-tmux-manager".flake = "github:RogerNavelsaker/nixpkg-named-tmux-manager"
"pi-coding-agent-rust".flake = "github:RogerNavelsaker/nixpkg-pi-coding-agent-rust"
"process-triage".flake = "github:RogerNavelsaker/nixpkg-process-triage"
"repo-updater".flake = "github:RogerNavelsaker/nixpkg-repo-updater"
"simultaneous-launch-button".flake = "github:RogerNavelsaker/nixpkg-simultaneous-launch-button"
"toon-rust".flake = "github:RogerNavelsaker/nixpkg-toon-rust"
"ultimate-bug-scanner".flake = "github:RogerNavelsaker/nixpkg-ultimate-bug-scanner"

[vars]
TERM = "xterm-256color"

[options]
systems = ["x86_64-linux"]
allow.unfree = true

[options.activate]
mode = "run"
